### ISSUE TITLE
About Custom Function: lcorner

### ISSUE THREAD

**Issue by persisli** [mdpetters/DifferentialMobilityAnalyzers.jl#17]
I can't understand: λopt = lcorner(0.01,1.0;n = 10,r = 3), and this function is not found in which library. How is this function calculated and defined?

**Comment by mdpetters** [comment]
The optimal λ is found using the L-curve method (Hansen 2000) and the iterative algorithm proposed by Talukdar and Swihart (2003). It is defined in ```src/regulariation.jl```

    lcorner(λ₁::AbstractFloat, λ₂::AbstractFloat; n::Int = 10, r::Int = 3)

Searches for the corner of the L-curve between λ₁ and λ₂. 
- n is the number of λs to divide between between λ₁ and λ₂. The alogorithm picks the best 
λ from these ten. Then it repeats for a narrower range of λ₁ and λ₂ around this best value
- r is the number of times to repeat the search

Example Usage
```julia
# R is the response vector
setupRegularization(δ.𝐀, δ.𝐈, R, inv(δ.𝐒) * R, n)  # setup the system
λopt = lcorner(λ₁, λ₂; n = 10, r = 3)              # compute the optimal λ
```

```julia
function lcorner(λ₁::AbstractFloat, λ₂::AbstractFloat; n::Int = 10, r::Int = 3)
    L1, L2, λs, ii = lcurve(λ₁, λ₂; n = n)
    for i = 1:r
        L1, L2, λs, ii = lcurve(λs[1], λs[3]; n = n)
    end
    return λs[2]
end
```

**Comment by persisli** [comment]
Thank you
